Fix pipelines

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,4 +12,4 @@ jobs:
         uses: ./
       - name: Gives a conclusion
         run: |
-          if [[ "${{ env.WORKFLOW_CONCLUSION }}" != "success" ]]; then echo "The pipeline failed" && exit 1; fi
+          if [[ "${{ env.WORKFLOW_CONCLUSION }}" != "skipped" ]]; then echo "The pipeline failed" && exit 1; fi
